@Compras.Api_HostAddress = http://localhost:5106

GET {{Compras.Api_HostAddress}}/api/purchases
Accept: application/json

###

POST {{Compras.Api_HostAddress}}/api/purchases
Content-Type: application/json

{
  "customerId": "d2719b41-4aa7-4a5b-9a3b-5e93c8af1b11",
  "currency": "USD",
  "items": [
    {
      "productId": "a22ee032-793b-4db2-920a-f4b7d2ec5b6e",
      "name": "Leche entera 1L",
      "unitPrice": 1.75,
      "quantity": 2
    }
  ]
}

###
