// <auto-generated />
using System;
using FacturacionElectronica.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FacturacionElectronica.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FacturacionElectronica.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Identificacion");

                    b.Property<string>("CodigoCiudad")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CodigoDepartamento")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CodigoPais")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RegistroMercantil")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ResponsabilidadFiscal")
                        .HasColumnType("int");

                    b.Property<int>("TipoPersona")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("FacturacionElectronica.Domain.Entities.DocumentoElectronico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ClienteId")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Cufe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmisorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRespuesta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaTransmision")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("QrCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RespuestaDian")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("int");

                    b.Property<string>("XmlContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XmlFirmado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaEmision");

                    b.HasIndex("NumeroDocumento")
                        .IsUnique();

                    b.HasIndex("ClienteId", "FechaEmision");

                    b.HasIndex("EmisorId", "FechaEmision");

                    b.ToTable("DocumentosElectronicos");
                });

            modelBuilder.Entity("FacturacionElectronica.Domain.Entities.Emisor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CertificadoDigital")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaveCertificado")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Nit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHabilitacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PinSoftware")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RegistroMercantil")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ResolucionHabilitacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ResponsabilidadFiscal")
                        .HasColumnType("int");

                    b.Property<string>("SoftwareId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TipoPersona")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Emisores");
                });

            modelBuilder.Entity("FacturacionElectronica.Domain.Entities.EventoDocumento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Detalles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId");

                    b.ToTable("EventosDocumentos");
                });

            modelBuilder.Entity("FacturacionElectronica.Domain.Entities.ImpuestoDocumento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoTributo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreTributo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Porcentaje")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("TipoImpuesto")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId");

                    b.ToTable("ImpuestosDocumentos");
                });

            modelBuilder.Entity("FacturacionElectronica.Domain.Entities.ItemDocumento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodigoEstandar")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<int>("UnidadMedida")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId");

                    b.ToTable("ItemsDocumentos");
                });

            modelBuilder.Entity("FacturacionElectronica.Domain.Entities.NumeracionDocumento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("EmisorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaAutorizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<long>("NumeroActual")
                        .HasColumnType("bigint");

                    b.Property<long>("NumeroFinal")
                        .HasColumnType("bigint");

                    b.Property<long>("NumeroInicial")
                        .HasColumnType("bigint");

                    b.Property<string>("Prefijo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ResolucionAutorizacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmisorId", "TipoDocumento", "Activo")
                        .HasFilter("[Activo] = 1");

                    b.ToTable("NumeracionesDocumentos");
                });

            modelBuilder.Entity("FacturacionElectronica.Domain.Entities.PagoDocumento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId");

                    b.ToTable("PagosDocumentos");
                });

            modelBuilder.Entity("FacturacionElectronica.Domain.Entities.Cliente", b =>
                {
                    b.OwnsOne("FacturacionElectronica.Domain.ValueObjects.InformacionContacto", "Contacto", b1 =>
                        {
                            b1.Property<Guid>("ClienteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("PaginaWeb")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<string>("Telefono")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.HasKey("ClienteId");

                            b1.ToTable("Clientes");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });

                    b.OwnsOne("FacturacionElectronica.Domain.ValueObjects.Direccion", "Direccion", b1 =>
                        {
                            b1.Property<Guid>("ClienteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Calle")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("Ciudad")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("CodigoPostal")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("Complemento")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("Departamento")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("Pais")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.HasKey("ClienteId");

                            b1.ToTable("Clientes");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });

                    b.Navigation("Contacto")
                        .IsRequired();

                    b.Navigation("Direccion")
                        .IsRequired();
                });

            modelBuilder.Entity("FacturacionElectronica.Domain.Entities.DocumentoElectronico", b =>
                {
                    b.HasOne("FacturacionElectronica.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Documentos")
                        .HasForeignKey("ClienteId")
                        .HasPrincipalKey("Codigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FacturacionElectronica.Domain.Entities.Emisor", "Emisor")
                        .WithMany()
                        .HasForeignKey("EmisorId")
                        .HasPrincipalKey("Codigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("FacturacionElectronica.Domain.ValueObjects.ValorMonetario", "SaldoPendiente", b1 =>
                        {
                            b1.Property<Guid>("DocumentoElectronicoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("DocumentoElectronicoId");

                            b1.ToTable("DocumentosElectronicos");

                            b1.WithOwner()
                                .HasForeignKey("DocumentoElectronicoId");
                        });

                    b.OwnsOne("FacturacionElectronica.Domain.ValueObjects.ValorMonetario", "Subtotal", b1 =>
                        {
                            b1.Property<Guid>("DocumentoElectronicoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("DocumentoElectronicoId");

                            b1.ToTable("DocumentosElectronicos");

                            b1.WithOwner()
                                .HasForeignKey("DocumentoElectronicoId");
                        });

                    b.OwnsOne("FacturacionElectronica.Domain.ValueObjects.ValorMonetario", "Total", b1 =>
                        {
                            b1.Property<Guid>("DocumentoElectronicoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("DocumentoElectronicoId");

                            b1.ToTable("DocumentosElectronicos");

                            b1.WithOwner()
                                .HasForeignKey("DocumentoElectronicoId");
                        });

                    b.OwnsOne("FacturacionElectronica.Domain.ValueObjects.ValorMonetario", "TotalDescuentos", b1 =>
                        {
                            b1.Property<Guid>("DocumentoElectronicoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("DocumentoElectronicoId");

                            b1.ToTable("DocumentosElectronicos");

                            b1.WithOwner()
                                .HasForeignKey("DocumentoElectronicoId");
                        });

                    b.OwnsOne("FacturacionElectronica.Domain.ValueObjects.ValorMonetario", "TotalImpuestos", b1 =>
                        {
                            b1.Property<Guid>("DocumentoElectronicoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("DocumentoElectronicoId");

                            b1.ToTable("DocumentosElectronicos");

                            b1.WithOwner()
                                .HasForeignKey("DocumentoElectronicoId");
                        });

                    b.OwnsOne("FacturacionElectronica.Domain.ValueObjects.ValorMonetario", "TotalPagado", b1 =>
                        {
                            b1.Property<Guid>("DocumentoElectronicoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("DocumentoElectronicoId");

                            b1.ToTable("DocumentosElectronicos");

                            b1.WithOwner()
                                .HasForeignKey("DocumentoElectronicoId");
                        });

                    b.Navigation("Cliente");

                    b.Navigation("Emisor");

                    b.Navigation("SaldoPendiente")
                        .IsRequired();

                    b.Navigation("Subtotal")
                        .IsRequired();

                    b.Navigation("Total")
                        .IsRequired();

                    b.Navigation("TotalDescuentos")
                        .IsRequired();

                    b.Navigation("TotalImpuestos")
                        .IsRequired();

                    b.Navigation("TotalPagado")
                        .IsRequired();
                });

            modelBuilder.Entity("FacturacionElectronica.Domain.Entities.Emisor", b =>
                {
                    b.OwnsOne("FacturacionElectronica.Domain.ValueObjects.InformacionContacto", "Contacto", b1 =>
                        {
                            b1.Property<Guid>("EmisorId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("PaginaWeb")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<string>("Telefono")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.HasKey("EmisorId");

                            b1.ToTable("Emisores");

                            b1.WithOwner()
                                .HasForeignKey("EmisorId");
                        });

                    b.OwnsOne("FacturacionElectronica.Domain.ValueObjects.Direccion", "Direccion", b1 =>
                        {
                            b1.Property<Guid>("EmisorId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Calle")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("Ciudad")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("CodigoPostal")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("Complemento")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("Departamento")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("Pais")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.HasKey("EmisorId");

                            b1.ToTable("Emisores");

                            b1.WithOwner()
                                .HasForeignKey("EmisorId");
                        });

                    b.Navigation("Contacto")
                        .IsRequired();

                    b.Navigation("Direccion")
                        .IsRequired();
                });

            modelBuilder.Entity("FacturacionElectronica.Domain.Entities.EventoDocumento", b =>
                {
                    b.HasOne("FacturacionElectronica.Domain.Entities.DocumentoElectronico", "Documento")
                        .WithMany("Eventos")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documento");
                });

            modelBuilder.Entity("FacturacionElectronica.Domain.Entities.ImpuestoDocumento", b =>
                {
                    b.HasOne("FacturacionElectronica.Domain.Entities.DocumentoElectronico", "Documento")
                        .WithMany("Impuestos")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FacturacionElectronica.Domain.ValueObjects.ValorMonetario", "BaseGravable", b1 =>
                        {
                            b1.Property<Guid>("ImpuestoDocumentoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("ImpuestoDocumentoId");

                            b1.ToTable("ImpuestosDocumentos");

                            b1.WithOwner()
                                .HasForeignKey("ImpuestoDocumentoId");
                        });

                    b.OwnsOne("FacturacionElectronica.Domain.ValueObjects.ValorMonetario", "Valor", b1 =>
                        {
                            b1.Property<Guid>("ImpuestoDocumentoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("ImpuestoDocumentoId");

                            b1.ToTable("ImpuestosDocumentos");

                            b1.WithOwner()
                                .HasForeignKey("ImpuestoDocumentoId");
                        });

                    b.Navigation("BaseGravable")
                        .IsRequired();

                    b.Navigation("Documento");

                    b.Navigation("Valor")
                        .IsRequired();
                });

            modelBuilder.Entity("FacturacionElectronica.Domain.Entities.ItemDocumento", b =>
                {
                    b.HasOne("FacturacionElectronica.Domain.Entities.DocumentoElectronico", "Documento")
                        .WithMany("Items")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FacturacionElectronica.Domain.ValueObjects.ValorMonetario", "Descuento", b1 =>
                        {
                            b1.Property<Guid>("ItemDocumentoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("ItemDocumentoId");

                            b1.ToTable("ItemsDocumentos");

                            b1.WithOwner()
                                .HasForeignKey("ItemDocumentoId");
                        });

                    b.OwnsOne("FacturacionElectronica.Domain.ValueObjects.ValorMonetario", "ValorTotal", b1 =>
                        {
                            b1.Property<Guid>("ItemDocumentoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("ItemDocumentoId");

                            b1.ToTable("ItemsDocumentos");

                            b1.WithOwner()
                                .HasForeignKey("ItemDocumentoId");
                        });

                    b.OwnsOne("FacturacionElectronica.Domain.ValueObjects.ValorMonetario", "ValorUnitario", b1 =>
                        {
                            b1.Property<Guid>("ItemDocumentoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("ItemDocumentoId");

                            b1.ToTable("ItemsDocumentos");

                            b1.WithOwner()
                                .HasForeignKey("ItemDocumentoId");
                        });

                    b.Navigation("Descuento");

                    b.Navigation("Documento");

                    b.Navigation("ValorTotal")
                        .IsRequired();

                    b.Navigation("ValorUnitario")
                        .IsRequired();
                });

            modelBuilder.Entity("FacturacionElectronica.Domain.Entities.NumeracionDocumento", b =>
                {
                    b.HasOne("FacturacionElectronica.Domain.Entities.Emisor", "Emisor")
                        .WithMany("Numeraciones")
                        .HasForeignKey("EmisorId")
                        .HasPrincipalKey("Codigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emisor");
                });

            modelBuilder.Entity("FacturacionElectronica.Domain.Entities.PagoDocumento", b =>
                {
                    b.HasOne("FacturacionElectronica.Domain.Entities.DocumentoElectronico", "Documento")
                        .WithMany("Pagos")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FacturacionElectronica.Domain.ValueObjects.ValorMonetario", "Valor", b1 =>
                        {
                            b1.Property<Guid>("PagoDocumentoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("PagoDocumentoId");

                            b1.ToTable("PagosDocumentos");

                            b1.WithOwner()
                                .HasForeignKey("PagoDocumentoId");
                        });

                    b.Navigation("Documento");

                    b.Navigation("Valor")
                        .IsRequired();
                });

            modelBuilder.Entity("FacturacionElectronica.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("FacturacionElectronica.Domain.Entities.DocumentoElectronico", b =>
                {
                    b.Navigation("Eventos");

                    b.Navigation("Impuestos");

                    b.Navigation("Items");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("FacturacionElectronica.Domain.Entities.Emisor", b =>
                {
                    b.Navigation("Numeraciones");
                });
#pragma warning restore 612, 618
        }
    }
}
